/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazejercicio8;

import javax.swing.JOptionPane;

/**
 *
 * @author walbonis1
 */
public class Ejercicio8 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio8
     */
    public Ejercicio8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadH = new javax.swing.JTextField();
        txtPagar = new javax.swing.JTextField();
        cmdBorrar = new javax.swing.JButton();
        cmboperacion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Universidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 210, 80));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cantida de horas: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtCantidadH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadHActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, -1));

        txtPagar.setEditable(false);
        txtPagar.setForeground(new java.awt.Color(204, 0, 0));
        txtPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagarActionPerformed(evt);
            }
        });
        jPanel1.add(txtPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, 30));

        cmdBorrar.setText("Borrar");
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        cmboperacion.setForeground(new java.awt.Color(0, 255, 204));
        cmboperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cantidad del descuento ", "total a pagar al profesor." }));
        cmboperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperacionActionPerformed(evt);
            }
        });
        jPanel1.add(cmboperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 170, 20));

        jButton1.setText("Total pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagarActionPerformed

    private void cmboperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String resultado;
       double ch,mp,nh,hora,descuento,op=0,result;
       int operacion;
       
       if(txtCantidadH.getText().isEmpty()){
           JOptionPane.showMessageDialog (this, "digite la cantidad de  hora ","error",JOptionPane.ERROR_MESSAGE);
           txtCantidadH.requestFocusInWindow();
           
           }
       else {
       
       
       mp =Double.parseDouble(txtCantidadH.getText());
       operacion= cmboperacion.getSelectedIndex();
       hora=20000*mp; 
       descuento=(hora*5)/100;
        result=mp+descuento;
       
       switch(operacion){
           case 0:
                   op = result; 
               break;
           case 1:
               op = descuento;
               break;
       }
       resultado =String.valueOf(operacion);
        txtPagar.setText(resultado); 
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCantidadHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboperacion;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidadH;
    private javax.swing.JTextField txtPagar;
    // End of variables declaration//GEN-END:variables
}
